setwd("C:/Users/artur/Desktop/Apu/APU/Lab5_1")
install.packages("C50")
library("C50")
library("MASS")
data("infert")
View(infert)
vars<-c("parity","case")
str(infert[, c(vars,"age")])
drzewo<-C5.0(x=infert[,vars], y=factor(infert$age))
summary(drzewo)
plot(drzewo)
ruleModeTree<-C5.0(x=infert[,vars], y=factor(infert$age), rules=TRUE)