install.packages("mlr")
library(mlr)
MacBook<-read.csv("macbook.csv")
MacBook=subset(MacBook,select=-c(nazwa,dysk,opinie))
MacBook$factors = factor(MacBook$factors) 
MacBook<-data.frame(MacBook) 
task = makeClassifTask(id = "Mac", data=MacBook, target="factors")
install.packages("rFerns")
install.packages("Rweka")
install.packages("extraTrees")
allLearners <- makeLearners(c("rFerns","adaboostm1","C50","ctree","extraTrees"), type = "classif") 
wynik <-benchmark(learners = allLearners, tasks = task, resampling = cv5)
save(wynik, file="wynik.rda")
load("wynik.rda")
wynik