install.packages("data.tree","formattable","DiagrammeR")
install.packages("data.tree","formattable","DiagrammeR")
install.packages("data.tree","formattable","DiagrammeR")
install.packages("data.tree","formattable","DiagrammeR")
install.packages("data.tree","formattable","DiagrammeR")
write('PATH="${RTOOLS40_HOME}\\usr\\bin;${PATH}"', file = "~/.Renviron", append = TRUE)
Sys.which("make")
install.packages("data.tree","formattable","DiagrammeR")
Sys.which("make")
install.packages("data.tree","formattable","DiagrammeR")
install.packages("data.tree")
install.packages("formattable")
install.packages("DiagrammeR")
install.packages('ahp')
install.packages("C:\Users\artur\Desktop\studia\ApuSprawko\ahp_0.2.12.tar.gz",repos=NULL,type = "source")
install.packages("C:/Users/artur/Desktop/studia/ApuSprawko/ahp_0.2.12.tar.gz",repos=NULL,type = "source")
setwd("C:\Users\artur\Desktop\studia\ApuSprawko\lab3\APU\neuralnet")
setwd("C:/Users/artur/Desktop/studia/ApuSprawko/lab3/APU/neuralnet")
setwd("C:/Users/artur/Desktop/studia/ApuSprawko/lab3/APU/neuralnet")
install.packages('neuralnet')
?neuralnet
??neuralnet
traininginput<- as.data.frame(runif(250,min = 0,max = 2*pi))
View(traininginput)
trainingoutput<-cos(traininginput)^sin(x)
trainingoutput<-cos(traininginput)^sin(traininginput)
View(trainingoutput)
View(traininginput)
View(trainingoutput)
View(traininginput)
maxs <- apply(traininginput,max)
maxs <- apply(traininginput,1,max)
maxs <- max(traininginput)
mins <- min(traininginput)
library("neuralnet")
min_max_norm <- function(x) {
(x - min(x)) / (max(x) - min(x))
}
min_max_norm <- function(x) {
(x - mins / (maxs - mins)
}
min_max_norm <- function(x) {
(x - mins / (maxs - mins))
}
MergedData <- cbind(traininginput,trainingoutput)
colnames(MergedData)<-c("InputData","FunctionData")
normalizedMergedData<-as.data.frame(lapply(MergedData,min_max_norm))
print(normalizedMergedData)
net.price <- neuralnet(InputData~FunctionData, normalizedMergedData, hidden = c(3,2), threshold = 0.01)
net.price <- neuralnet(InputData~FunctionData, normalizedMergedData, hidden = c(3,2), threshold = 0.01)
View(normalizedMergedData)
cleanData <- normalizedMergedData[df$FunctionData != "NaN"]
cleanData <- normalizedMergedData[normalizedMergedData$FunctionData != "NaN"]
cleanData <- normalizedMergedData[normalizedMergedData$FunctionData != NaN]
cleanData <- normalizedMergedData[normalizedMergedData$InputData,normalizedMergedData$FunctionData != NaN]
library(tidyverse)
library("tidyverse")
install.packages("tidyverse")
library(tidyverse)
cleanTrainingData <- normalizedMergedData %>% filter(FunctionData != NaN)
View(cleanTrainingData)
cleanTrainingData <- normalizedMergedData %>% filter(FunctionData != "NaN")
net.price <- neuralnet(InputData~FunctionData, cleanTrainingData , hidden = c(3,2), threshold = 0.01)
plot(net.price)
View(net.price)
View(cleanTrainingData)
View(cleanTrainingData)
net.price <- neuralnet(InputData~FunctionData, cleanTrainingData , hidden = c(4,5,3), threshold = 0.01)
View(net.price)
plot(net.price)
net.price <- neuralnet(InputData~FunctionData, cleanTrainingData , hidden = c(4,5,3), threshold = 0.01, stepmax=1e7)
net.price <- neuralnet(InputData~FunctionData, cleanTrainingData , hidden = c(3,2), threshold = 0.01, stepmax=1e7)
traininginput<- as.data.frame(runif(100,min = 0,max = 2*pi))
View(traininginput)
trainingoutput<-cos(traininginput)^sin(traininginput)
View(trainingoutput)
MergedData <- cbind(traininginput,trainingoutput)
colnames(MergedData)<-c("InputData","FunctionData")
normalizedMergedData<-as.data.frame(lapply(MergedData,min_max_norm)
normalizedMergedData<-as.data.frame(lapply(MergedData,min_max_norm)
normalizedMergedData<-as.data.frame(lapply(MergedData,min_max_norm))
cleanTrainingData <- normalizedMergedData %>% filter(FunctionData != "NaN")
net.price <- neuralnet(InputData~FunctionData, cleanTrainingData , hidden = c(3,2), threshold = 0.01, stepmax=1e7)
traininginput<- as.data.frame(runif(60,min = 0,max = 2*pi))
View(traininginput)
trainingoutput<-cos(traininginput)^sin(traininginput)
View(trainingoutput)
maxs <- max(traininginput)
mins <- min(traininginput)
maxs <- max(traininginput)
mins <- min(traininginput)
MergedData <- cbind(traininginput,trainingoutput)
colnames(MergedData)<-c("InputData","FunctionData")
normalizedMergedData<-as.data.frame(lapply(MergedData,min_max_norm))
cleanTrainingData <- normalizedMergedData %>% filter(FunctionData != "NaN")
net.price <- neuralnet(InputData~FunctionData, cleanTrainingData , hidden = c(3,2), threshold = 0.01, stepmax=1e7)
net.price <- neuralnet(InputData~FunctionData, cleanTrainingData , hidden = c(3,4,3), threshold = 0.01)
traininginput<- as.data.frame(runif(30,min = 0,max = 2*pi))
View(traininginput)
trainingoutput<-cos(traininginput)^sin(traininginput)
View(trainingoutput)
maxs <- max(traininginput)
mins <- min(traininginput)
MergedData <- cbind(traininginput,trainingoutput)
colnames(MergedData)<-c("InputData","FunctionData")
normalizedMergedData<-as.data.frame(lapply(MergedData,min_max_norm))
cleanTrainingData <- normalizedMergedData %>% filter(FunctionData != "NaN")
net.price <- neuralnet(InputData~FunctionData, cleanTrainingData , hidden = c(3,2), threshold = 0.01, stepmax=1e7)
plot(net.price)
save.image(file = "Lab4.RData")
savehistory('history')
savehistory('history.R')
MacBook<-read.csv("macbook.csv")
View(MacBook)
normalizedDisplay <- normalize(MacBook$ekran)
normalizedDisplay <- normalize(MacBook$ekran)
normalizedDisplay <- min_max_norm(MacBook$ekran)
normalizedPrice <- min_max_norm(MacBook$cena)
normalizedDisc <- min_max_norm(MacBook$dysk)
normalizedDisc <- min_max_norm(MacBook$dysk)
normalizedDisc <- min_max_norm(MacBook$RAM)
MacBook <- MacBook[,-1]
MergedDataMac<- cbind(normalizedDisc,normalizedDisplay,normalizedPrice)
net2.price <- neuralnet(cena~RAM+ekran,MergedDataMac,hidden=c(2,4,3), threshold = 100)
View(MergedDataMac)
net2.price <- neuralnet(normalizedPrice~normalizedDisc+normalizedDisplay,MergedDataMac,hidden=c(2,4,3), threshold = 100)
plot(net2.price)
net2.price <- neuralnet(normalizedPrice~normalizedDisc+normalizedDisplay,MergedDataMac,hidden=c(2,4,3), threshold = 0.01)
plot(net2.price)
net2.price <- neuralnet(normalizedPrice~normalizedDisc+normalizedDisplay,MergedDataMac,hidden=c(2,4,3), threshold = 0.001)
plot(net2.price)
net2.price <- neuralnet(normalizedPrice~normalizedDisc+normalizedDisplay,MergedDataMac,hidden=c(2,4,3), threshold = 100)
plot(net2.price)
save.image(file = "Lab4.RData")
savehistory('history.R')
